apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: entando-devs-roma-
spec:
    serviceAccountName: build-bot
    pipelineRef:
      name: entando-dependency
    params:
      - name: repo-url
        value: ssh://git@github.com:entando/entando-components.git
      - name: subdir-path
        value: ""
      - name: branch-name
        value: preprod
      - name: clean-workspace
        value: "true"
    workspaces:
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 100Mi
      - name: ssh-creds
        secret:
          secretName: ssh-key
