apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: cleanup
spec:
  steps:
    - name: remove-source
      image: alpine
      command:
        - /bin/sh
      args:
        - -c
        - "rm -rf /workspace/source"
    - name: message
      image: alpine
      command:
        - /bin/sh
      args:
        - -c
        - "echo All files were deleted"
