apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: uninstall-entando
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: |
    This task uninstall an Entando instance within the current namespace:
  params:
    - name: image
      default: gcr.io/cloud-builders/kubectl@sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753 #image is huge
      description: kubectl wrapper image # We need to update the default one for sure
  steps:
    - name: uninstall-entando
      image: $(params.image)
      script: |
        #!/usr/bin/env bash
        set -xe
        
        #Delete Enap
        kubectl delete enap --all
        
        # Delete the bundle
        kubectl delete entandodebundle --all
        
        # Delete plugin links
        kubectl delete elnk --all
        
        # Delete the operator configmap
        kubectl delete configmap --all
        
        # Delete the entando plugins
        kubectl delete eps --all
        
        # Delete the kc provided capability
        kubectl delete pcs --all
        
        # Delete all the deployments
        kubectl delete deploy --all
        
        # Delete k8s-service
        kubectl delete service --all
        
