apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: el-gitlab
spec:
  ingressClassName: nginx
  rules:
    - host: #<your FQDN>
      http:
        paths:
          - path: /99f8c806ee87fa679ce695ffd9e59f95 # difficult to guess path
            pathType: ImplementationSpecific
            backend:
              service:
                name: el-gitlab-event-listener
                port:
                  number: 8080

