apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-access
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - extentions
      - policy
      - rbac.authorization.k8s.io
      - roles.rbac.authorization.k8s.io
      - entando.org
      - security.openshift.io
      - networking.k8s.io
      - extensions
      - route.openshift.io
    resources:
      - roles
      - rolebindings
      - configmaps
      - serviceaccounts
      - pods
      - deployments
      - services
      - entandodebundles
      - securitycontextconstraints
      - ingresses
      - namespaces
      - secrets
    verbs: ["*"]
