apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com
    tekton.dev/git-1: gitlab.com
data:
  id_rsa: # cat ~/.ssh/id_rsa
  config: # cat ~/.ssh/config
  known_hosts: #cat ~/.ssh/known_hosts
